Integrate identify snap
hashgraph/hedera-metamask-snaps pull request #735
Opened 2024-10-11 19:53 UTC by himalayan-dev

## Description

This pull request changes the following:

- Integrate the identify snap onto the hashgraph repo

### Related Issues

2024-10-11 19:59 UTC, kpachhai submitted a review, later dismissed

2024-10-11 21:39 UTC, kpachhai approved these changes, later dismissed

2024-10-15 03:25 UTC, Nana-EC requested changes
Big step 🙌🏾 , let's add some missing repo items though.

2024-10-15 03:25 UTC, Nana-EC commented on packages/hedera-identify-snap/README.md
> +# Hedera Wallet Snap for MetaMask
Contents of this file are incorrect and need to match the identify-snap

2024-10-15 03:25 UTC, Nana-EC commented on packages/hedera-identify-snap/packages/site/README.md
> +
Would be useful to have a paragraph highlighting the website functionality and a section for technologies utilized

2024-10-15 03:25 UTC, Nana-EC commented on packages/hedera-identify-snap/packages/site/gatsby-ssr.tsx
> + * Hedera Wallet Snap
Update all license headers to be correct for this package
```suggestion
 * Hedera Identify Snap
```

2024-10-15 03:25 UTC, Nana-EC commented on packages/hedera-identify-snap/packages/site/src/components/base/Buttons.tsx
> +import { ComponentProps } from 'react';
tsx files are missing header licenses

2024-10-15 03:25 UTC, Nana-EC commented on packages/hedera-identify-snap/packages/snap/src/hedera/client/index.ts
> +import {
Missing license headers in ts files

2024-10-15 14:04 UTC, kpachhai approved these changes

2024-10-16 19:23 UTC, kpachhai submitted a review, later dismissed

2024-10-17 18:30 UTC, kpachhai approved these changes

2024-10-19 03:14 UTC, Nana-EC approved these changes

2024-10-19 11:11 UTC, merged